# Autogenerated at 04.07.2022 19:08 using ./gen-makefile.sh

## apache: Install apache2 (latest)
apache:
	./install/apache.sh

## apt: Install bunch of software from apt
apt:
	./install/apt.sh

## chrome: Install google chrome (latest)
chrome:
	./install/chrome.sh

## composer: Install composer (latest)
composer:
	./install/composer.sh

## docker: Install docker (latest) + docker-compose (latest) + ppa
docker:
	./install/docker.sh

## droidcam-obs: Install droidcam-obs plugin v1.5.1
droidcam-obs:
	./install/droidcam-obs.sh

## droidcam: Install droidcam v1.8.2
droidcam:
	./install/droidcam.sh

## git: Install git (latest)
git:
	./install/git.sh

## golang: Install golang v1.18.3
golang:
	./install/golang.sh

## grubc: Install grub-customizer (latest) + ppa
grubc:
	./install/grubc.sh

## kde-appmenu: Install KDE Window AppMenu Applet
kde-appmenu:
	./install/kde-appmenu.sh

## lite-xl: Install lite-xl v2.0.5 (draft)
lite-xl:
	./install/lite-xl.sh

## mariadb: Install mariadb (latest) and php-mysql + phpMyAdmin (if php is installed)
mariadb:
	./install/mariadb.sh

## nodejs: Install nodejs + npm via nvm
nodejs:
	./install/nodejs.sh

## pgsql: Install postgresql (latest) and php-pgsql (if php is installed)
pgsql:
	./install/pgsql.sh

## php: Install php v8.1 + ppa
php:
	./install/php.sh

## postman: Install postman (latest)
postman:
	./install/postman.sh

## rustdesk: Install rustdesk v1.1.8 (deb)
rustdesk:
	./install/rustdesk.sh

## snap: Install bunch of software from snap
snap:
	./install/snap.sh

## syncthing: Install syncthing (latest) + ppa
syncthing:
	./install/syncthing.sh

## telebit: Install telebit (latest)
telebit:
	./install/telebit.sh

## ulauncher: Install ulauncher (latest) + ppa
ulauncher:
	./install/ulauncher.sh

## wine: Installwine (latest) + ppa (focal)
wine:
	./install/wine.sh

## zint: Install zint (latest)
zint:
	./install/zint.sh

## zsh: Install zsh + omz (latest)
zsh:
	./install/zsh.sh

## help: Show this help message
help: Makefile
	@echo "Usage:"
	@echo "\tmake <goal>\n"
	@echo "Available goals:"
	@sed -n 's/^##//p' $< | column -t -s ':' |  sed -e "s/^/\t/"

## <goal>_: Same as 'cat ./install/<goal>.sh'
%_:
	@cat ./install/$*.sh
