# Autogenerated at 05.07.2022 10:52 using ./gen-makefile

##flameshot: [TODO] [PACK] qt5 + flameshot from source
flameshot: qt5 flameshot-build

##lamp: [PACK] Apache + php + mariadb
lamp: apache php mariadb

##omz: [PACK] zsh + omz + powerline10k + MesloLGS fonts
omz: zsh omz-clean

##apache: Install apache2 (latest)
apache:
	./install/apache

##apt: Install bunch of software from apt
apt:
	./install/apt

##chrome: Install google chrome (latest)
chrome:
	./install/chrome

##composer: Install composer (latest)
composer:
	./install/composer

##docker: Install docker (latest) + docker-compose (latest) + ppa
docker:
	./install/docker

##droidcam: Install droidcam v1.8.2
droidcam:
	./install/droidcam

##droidcam-obs: Install droidcam-obs plugin v1.5.1
droidcam-obs:
	./install/droidcam-obs

##flameshot-build: [TODO] Build flameshot from src (latest)
flameshot-build:
	./install/flameshot-build

##git: Install git (latest)
git:
	./install/git

##golang: Install golang v1.18.3
golang:
	./install/golang

##grubc: Install grub-customizer (latest) + ppa
grubc:
	./install/grubc

##kde-appmenu: Install KDE Window AppMenu Applet
kde-appmenu:
	./install/kde-appmenu

##libreoffice: Install libreoffice
libreoffice:
	./install/libreoffice

##lite-xl: Install lite-xl v2.0.5 (draft)
lite-xl:
	./install/lite-xl

##mariadb: Install mariadb (latest) and php-mysql + phpMyAdmin (if php is installed)
mariadb:
	./install/mariadb

##nodejs: Install nodejs + npm via nvm
nodejs:
	./install/nodejs

##omz-clean: Install omz (latest) + powerline10k + MesloLGS fonts
omz-clean:
	./install/omz-clean

##papirus: Install papirus-icon-theme (latest)
papirus:
	./install/papirus

##pgsql: Install postgresql (latest) and php-pgsql (if php is installed)
pgsql:
	./install/pgsql

##php: Install php v8.1 + ppa
php:
	./install/php

##postman: Install postman (latest)
postman:
	./install/postman

##qt5: Install qt5
qt5:
	./install/qt5

##rustdesk: Install rustdesk client v1.1.9 (deb)
rustdesk:
	./install/rustdesk

##snap: Install bunch of software from snap
snap:
	./install/snap

##syncthing: Install syncthing (latest) + ppa
syncthing:
	./install/syncthing

##telebit: Install telebit (latest)
telebit:
	./install/telebit

##ulauncher: Install ulauncher (latest) + ppa
ulauncher:
	./install/ulauncher

##wine: Install wine (latest) + ppa (focal)
wine:
	./install/wine

##zint: Install zint (latest)
zint:
	./install/zint

##zsh: Install vanilla zsh
zsh:
	./install/zsh

##help: Show this help message
help: Makefile
	@echo "Usage:"
	@echo "\tmake <goal>\n"
	@echo "Available goals:"
	@sed -n 's/^##//p' $< | column -t -s ':' |  sed -e "s/^/\t/"

##<goal>_: Same as 'cat ./install/<goal>'
%_:
	@cat ./install/$*
