#!/bin/bash
##makedesc: Install apache2 (latest)
source "$( dirname $(readlink -e -- "${BASH_SOURCE}"))/../helpers.sh" || exit 255

title

apt_install apache2
sudo systemctl restart apache2

success "apache2 installed!"
apache2 -v
