#!/bin/bash
##makedesc: Install bunch of software from apt

echo
echo "==============================================="
echo "Installing software from apt..."
echo "==============================================="
echo

sudo apt update && \
    sudo apt upgrade -y --autoremove

sudo apt install -y \
    alien \
    apt-transport-https \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    dconf-editor \
    default-jdk \
    dialog \
    gettext \
    gnupg \
    gparted \
    hardinfo \
    htop \
    libaio1 \
    libcurl4-gnutls-dev \
    libexpat1-dev \
    libghc-zlib-dev \
    libreoffice \
    libssl-dev \
    lsb-release \
    lsp-plugins \
    make \
    mc \
    meld \
    nano \
    neofetch \
    net-tools \
    nmap \
    p7zip-full \
    pulseeffects \
    software-properties-common \
    sqlitebrowser \
    terminator \
    ubuntu-restricted-extras \
    unzip \
    vlc \
    # at \
    # compiz \
    # compizconfig-settings-manager \
    # deepin-screenshot \
    # earlyoom \
    # etckeeper \
    # geoclue-2.0 \
    # gnome-software \
    # minder \
    # nodejs \
    # redshift \
    # redshift-gtk
