#!/bin/bash
##makedesc: Install docker (latest) + docker-compose (latest) + ppa
source `dirname $0`/../helpers || exit 255

# https://docs.docker.com/engine/install/ubuntu/

title

require ca-certificates
require curl
require gnupg
require lsb-release

sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
| sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    sudo chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    sudo apt update && \
    sudo apt install -y --autoremove \
        docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-compose-plugin && \
    sudo usermod -aG docker $(whoami)

[ $? = 0 ] && {
    echo
    success "Docker installed!"
    info "Probably, you need to relogin to apply 'docker' group."
    info "Your ones currently are: $(groups)"
    docker --version
    echo
}
