#!/bin/bash
##makedesc: Install droidcam v1.9.0
source `dirname $0`/../helpers || exit 255

# https://www.dev47apps.com/droidcam/linux/

title

mkdir -p "$HOME/install/droidcam"

download "https://files.dev47apps.net/linux/droidcam_1.9.0.zip" "$HOME/install/droidcam.zip" && \
    unzip -oq "$HOME/install/droidcam.zip" -d "$HOME/install/droidcam" && \
    cd "$HOME/install/droidcam" && \
    sudo ./install-client

[ $? = 0 ] && {
    echo
    success "droidcam installed!"
    info "Don't forget to install the android app:"
    info "https://play.google.com/store/apps/developer?id=Dev47Apps"
    echo
}
