#!/bin/bash
##makedesc: Install droidcam v1.8.2

# https://www.dev47apps.com/droidcam/linux/

echo
echo "==============================================="
echo "Installing droidcam v1.8.2..."
echo "==============================================="
echo

mkdir -p ~/install/droidcam
wget -O /tmp/droidcam.zip https://files.dev47apps.net/linux/droidcam_1.8.2.zip
unzip -oq /tmp/droidcam.zip -d ~/install/droidcam
rm -rf /tmp/droidcam.zip
cd ~/install/droidcam && sudo ./install-client

echo
echo "Don't forget to install android app: https://play.google.com/store/apps/developer?id=Dev47Apps"
echo
