#!/bin/bash
##makedesc: [TODO] Build flameshot from src (latest)

echo
echo "==============================================="
echo "Installing flameshot (latest)..."
echo "==============================================="
echo
