#!/bin/bash
##makedesc: Install grub-customizer (latest) + ppa

echo
echo "==============================================="
echo "Installing grub-customizer (latest)..."
echo "==============================================="
echo

sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer
sudo apt install -y --autoremove grub-customizer
