#!/bin/bash
##makedesc: Install grub-customizer (latest + ppa)
source `dirname $0`/../helpers || exit 255

title

sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer && \
    sudo apt install -y --autoremove grub-customizer

[ $? = 0 ] && {
    echo
    success "grub-customizer installed!"
    grub-customizer -v
    echo
}
