#!/bin/bash
##makedesc: Install JetBrains Mono fonts

# https://www.jetbrains.com/lp/mono/#how-to-install

echo
echo "==============================================="
echo "Installing JetBrains Mono fonts..."
echo "==============================================="
echo

installed() {
    command -v "$1" >/dev/null 2>&1
}

! installed wget && sudo apt install wget
! installed unzip && sudo apt install unzip

mkdir -p "$HOME/install/jbmono" "$HOME/.local/share/fonts/"
wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip -O "$HOME/install/jbmono.zip" && \
    unzip -oj "$HOME/install/jbmono.zip" "fonts/ttf/*.ttf" -d "$HOME/.local/share/fonts/" && \
    fc-cache -vf "$HOME/.local/share/fonts/"
