#!/bin/bash
##makedesc: Install KDE Backports
source `dirname $0`/../helpers || exit 255

title

sudo add-apt-repository -y ppa:kubuntu-ppa/backports && \
    sudo apt update && \
    sudo apt full-upgrade
