#!/bin/bash
##makedesc: Install KDE Backports

echo
echo "==============================================="
echo "Installing KDE Backports..."
echo "==============================================="
echo

sudo add-apt-repository -y ppa:kubuntu-ppa/backports
# sudo add-apt-repository -y ppa:kubuntu-ppa/backports-extra
sudo apt update
# sudo pkcon update
sudo apt full-upgrade
