#!/bin/bash
##makedesc: Install KDE Backports
source "$( dirname $(readlink -e -- "${BASH_SOURCE}"))/../helpers.sh" || exit 255

title

sudo add-apt-repository -y ppa:kubuntu-ppa/backports && \
    sudo apt update && \
    sudo apt full-upgrade
