#!/bin/bash
##makedesc: Install omz (latest)

echo
echo "==============================================="
echo "Installing omz (latest)..."
echo "==============================================="
echo

installed() {
    command -v "$1" >/dev/null 2>&1
}

if ! installed zsh || ! installed git || ! installed curl; then
    echo "ERROR: you need git, zsh and curl to be installed!"
    exit 1
fi

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
