#!/bin/bash
##makedesc: Install papirus-icon-theme (latest)
source `dirname $0`/../helpers || exit 255

title

mkdir -p "$HOME/install/papirus-icon-theme" "$HOME/.local/share/icons/"

if installed git; then
    clone_quick https://github.com/PapirusDevelopmentTeam/papirus-icon-theme.git "$HOME/install/"
else
    download https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/refs/heads/master.zip -O "$HOME/install/papirus-icon-theme.zip" && \
        unzip -oq "$HOME/install/papirus-icon-theme.zip" -d "$HOME/install/papirus-icon-theme" && \
        rm -f "$HOME/install/papirus-icon-theme.zip"
fi

symlink "$HOME/install/papirus-icon-theme/Papirus" "$HOME/.local/share/icons/Papirus" && \
    symlink "$HOME/install/papirus-icon-theme/Papirus-Dark" "$HOME/.local/share/icons/Papirus-Dark" && \
    symlink "$HOME/install/papirus-icon-theme/Papirus-Light" "$HOME/.local/share/icons/Papirus-Light"

[ $? = 0 ] && {
    echo
    success "Papirus icons installed!"
    info "You can find them in $HOME/.local/share/icons/"
    echo
}

