#!/bin/bash
##makedesc: Install postgresql (latest) and php-pgsql (if php is installed)
source `dirname $0`/../helpers || exit 255

title

require postgresql postgresql-contrib && \
    sudo service postgresql restart && \
    {
        echo
        success "openvpn installed!"
        postgres --version
        echo
    }
