#!/bin/bash
##makedesc: Install php v8.1 + ppa

[ $1 ] && PHPVER="$1" || PHPVER="8.1"
echo
echo "==============================================="
echo "Installing php${PHPVER}..."
echo "==============================================="
echo

sudo LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
sudo apt install -y --autoremove \
    php${PHPVER} \
    php${PHPVER}-apcu \
    php${PHPVER}-bcmath \
    php${PHPVER}-cli \
    php${PHPVER}-common \
    php${PHPVER}-curl \
    php${PHPVER}-dev \
    php${PHPVER}-dom \
    php${PHPVER}-gd \
    php${PHPVER}-intl \
    php${PHPVER}-mbstring \
    php${PHPVER}-mysql \
    php${PHPVER}-opcache \
    php${PHPVER}-pgsql \
    php${PHPVER}-soap \
    php${PHPVER}-sqlite3 \
    php${PHPVER}-xdebug \
    php${PHPVER}-xml \
    php${PHPVER}-xmlrpc \
    php${PHPVER}-zip

    # php${PHPVER}-ldap \
    # php${PHPVER}-dba \
    # php${PHPVER}-xsl \

php -v
