#!/bin/bash
##makedesc: Install phpstan

echo
echo "==============================================="
echo "Installing phpstan..."
echo "==============================================="
echo

installed() {
    command -v "$1" >/dev/null 2>&1
}

! installed 'php' && echo 'ERROR: You need php to be installed' && exit 1
! installed "composer" && echo "ERROR: You need composer to be installed" && exit 2

COMPOSER_GLOBAL_HOME="$(composer config -g home)"
NEWPATH="export PATH=\"$COMPOSER_GLOBAL_HOME/vendor/bin:\${PATH}\""
cat "$HOME/.profile" | grep -qoh "$NEWPATH" || {
    $NEWPATH
    echo "$NEWPATH" >> "$HOME/.profile"
}
source "$HOME/.profile"

composer global require phpstan/phpstan --dev

echo
echo "Finish!"
phpstan --version
echo

