#!/bin/bash
##makedesc: Install rustdesk client v1.1.9 (deb)

[ $1 ] && RDVER="$1" || RDVER="1.1.9"
echo
echo "==============================================="
echo "Installing rustdesk v${RDVER}..."
echo "==============================================="
echo

# https://github.com/rustdesk/rustdesk

sudo apt install libxdo3 && \
    wget "http://github.com/rustdesk/rustdesk/releases/download/${RDVER}/rustdesk-${RDVER}.deb" -O ${HOME}/install/rustdesk_${RDVER}.deb && \
    sudo dpkg -i ${HOME}/install/rustdesk_${RDVER}.deb
