#!/bin/bash
##makedesc: Install bunch of software from snap

echo
echo "==============================================="
echo "Installing software from snap..."
echo "==============================================="
echo

installed() {
    command -v "$1" >/dev/null 2>&1
}

snapi() {
    snap install $1 2>/dev/null
    [[ $? -ne 0 ]] && snap install $1 --classic
}

if ! installed snapd; then
    sudo apt update
    sudo apt install -y --autoremove snapd #gnome-software-plugin-snap
fi

# snapi snap-store
# snapi gtk-common-themes
# snapi gtk2-common-themes

snapi peek
# snapi telegram-desktop #todo
# snapi code # deb https://github.com/microsoft/vscode/issues/221836
snapi skype
snapi dbeaver-ce
# snapi mysql-workbench-community
# snapi discord
# snapi phpstorm
# snapi audacity
# snapi flameshot # deb
# snapi zoom-client # deb

# https://certbot.eff.org/
# snapi certbot
# sudo ln -sf /snap/bin/certbot /usr/bin/certbot

