#!/bin/bash
##makedesc: VSCode deb-package
source `dirname $0`/../helpers || exit 255

title

mkdir -p "$HOME/install"

download "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64" \
    "$HOME/install/vscode.deb" && \
    sudo dpkg -i "$HOME/install/vscode.deb"

[ $? = 0 ] && {
    echo
    success "VSCode installed"
    code --version
    echo
}
