#!/bin/bash
##makedesc: Install vanilla zsh

echo
echo "==============================================="
echo "Installing vanilla zsh..."
echo "==============================================="
echo

sudo apt install -y --autoremove zsh
echo "source ~/.profile" >> ~/.zshrc
