#!/bin/bash
##makedesc: Uninstall apache2
source `dirname $0`/../helpers || exit 255

title

sudo apt remove -y --autoremove apache2

[ $? = 0 ] && {
    echo
    success "apache2 uninstalled!"
    echo
}
