#!/bin/bash
##makedesc: Uninstall docker

echo
echo "==============================================="
echo "Uninstalling docker..."
echo "==============================================="
echo

# sudo apt remove -y docker docker-engine docker.io containerd runc
sudo apt remove -y \
  containerd \
  containerd.io \
  docker \
  docker-ce \
  docker-ce-cli \
  docker-compose \
  docker-compose-plugin \
  docker-engine \
  docker.io \
  runc
