#!/bin/bash
##makedesc: Uninstall docker + ppa

echo
echo "==============================================="
echo "Uninstalling docker + ppa..."
echo "==============================================="
echo

sudo apt remove -y docker*

rm -rf \
    /etc/apt/sources.list.d/docker.list \
    /etc/apt/keyrings/docker.gpg

sudo apt update
