#!/bin/bash
##makedesc: Uninstall docker + ppa
source "$( dirname $(readlink -e -- "${BASH_SOURCE}"))/../helpers.sh" || exit 255

title

apt_remove -y \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin \
    docker-ce-rootless-extras

sudo rm -rf \
    /var/lib/docker \
    /var/lib/containerd \
    /etc/apt/sources.list.d/docker.list \
    /etc/apt/keyrings/docker.asc

apt_update
