#!/bin/bash
##makedesc: Uninstall omz

echo
echo "==============================================="
echo "Uninstalling omz..."
echo "==============================================="
echo

bash $ZSH/tools/uninstall.sh
exec bash
